apiVersion: v1

kind: Service 

metadata:
  name: patch-management-services
  labels:
    app: patch-management-services-svc-label

spec:
  ports:
  - port: 8081
    name: http

  selector:
    app: patch-management-services-v1-v2

  type: LoadBalancer

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: patch-management-services-deployment-v1
  labels:
    app: patch-management-services-dep-label

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: patch-management-services-v1-v2

  template: # template for the pods
    metadata:
      labels:
        app: patch-management-services-v1-v2
        version: v1

    spec:
      containers:
      - name: patch-management-services-ver1
        image: docker.io/saurabh2204/patch-management-services:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8897
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m        
